# Generated by Django 3.2.14 on 2023-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20230218_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_id',
            field=models.CharField(default='shiekhahmadkftaro', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
