# Generated by Django 3.2.14 on 2023-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_category_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('ch_id', models.CharField(max_length=1000, unique=True)),
                ('slug', models.SlugField(max_length=1000)),
            ],
        ),
    ]
