# Generated by Django 3.2.14 on 2023-03-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_auto_20230311_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Photo', 'Photo'), ('Audio', 'Audio')], default='Video', max_length=100),
            preserve_default=False,
        ),
    ]
