# Generated by Django 3.2.14 on 2023-03-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0006_category_cat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
